QT += widgets xml uitools concurrent
# requires(qtConfig(listview))

CONFIG += c++17

INCLUDEPATH += src/core src/gui external/QtAppSetup/src build/bin/core

LIBS += -lz

SOURCES = \
src/android/main.cpp \
external/QtAppSetup/src/app/cli.cpp \
external/QtAppSetup/src/app/settings/palette_settings.cpp \
external/QtAppSetup/src/app/settings/settings.cpp \
external/QtAppSetup/src/app/settings/keyboard_shortcuts_model.cpp \
external/QtAppSetup/src/app/settings/keyboard_shortcuts.cpp \
external/QtAppSetup/src/app/scripting/script_engine.cpp \
external/QtAppSetup/src/app/widgets/widget_palette_editor.cpp \
external/QtAppSetup/src/app/widgets/keyboard_settings_widget.cpp \
external/QtAppSetup/src/app/widgets/clearable_keysequence_edit.cpp \
external/QtAppSetup/src/app/widgets/settings_dialog.cpp \
external/QtAppSetup/src/app/log/log_model.cpp \
external/QtAppSetup/src/app/log/logger.cpp \
external/QtAppSetup/src/app/translation_service.cpp \
external/QtAppSetup/src/app/application.cpp \
src/core/app_info.cpp \
src/core/command/structure_commands.cpp \
src/core/command/shape_commands.cpp \
src/core/command/animation_commands.cpp \
src/core/io/lottie/lottie_format.cpp \
src/core/io/lottie/lottie_html_format.cpp \
src/core/io/lottie/tgs_format.cpp \
src/core/io/lottie/cbor_write_json.cpp \
src/core/io/glaxnimate/glaxnimate_format.cpp \
src/core/io/glaxnimate/glaxnimate_importer.cpp \
src/core/io/glaxnimate/glaxnimate_mime.cpp \
src/core/io/svg/svg_renderer.cpp \
src/core/io/svg/svg_parser.cpp \
src/core/io/svg/detail.cpp \
src/core/io/svg/svg_format.cpp \
src/core/io/mime/mime_serializer.cpp \
src/core/io/raster/raster_format.cpp \
src/core/io/base.cpp \
src/core/math/geom.cpp \
src/core/math/ellipse_solver.cpp \
src/core/math/bezier/bezier.cpp \
src/core/math/bezier/point.cpp \
src/core/math/bezier/operations.cpp \
src/core/math/bezier/cubic_struts.cpp \
src/core/math/bezier/meta.cpp \
src/core/model/main_composition.cpp \
src/core/model/composition.cpp \
src/core/model/document.cpp \
src/core/model/document_node.cpp \
src/core/model/object.cpp \
src/core/model/transform.cpp \
src/core/model/factory.cpp \
src/core/model/animation_container.cpp \
src/core/model/stretchable_time.cpp \
src/core/model/comp_graph.cpp \
src/core/model/mask_settings.cpp \
src/core/model/visitor.cpp \
src/core/model/animation/keyframe_transition.cpp \
src/core/model/animation/animatable.cpp \
src/core/model/animation/animatable_path.cpp \
src/core/model/property/property.cpp \
src/core/model/property/reference_property.cpp \
src/core/model/property/option_list_property.cpp \
src/core/model/assets/assets.cpp \
src/core/model/assets/brush_style.cpp \
src/core/model/assets/named_color.cpp \
src/core/model/assets/bitmap.cpp \
src/core/model/assets/gradient.cpp \
src/core/model/assets/asset_base.cpp \
src/core/model/assets/asset.cpp \
src/core/model/assets/precomposition.cpp \
src/core/model/shapes/shape.cpp \
src/core/model/shapes/fill.cpp \
src/core/model/shapes/rect.cpp \
src/core/model/shapes/group.cpp \
src/core/model/shapes/ellipse.cpp \
src/core/model/shapes/path.cpp \
src/core/model/shapes/stroke.cpp \
src/core/model/shapes/polystar.cpp \
src/core/model/shapes/styler.cpp \
src/core/model/shapes/layer.cpp \
src/core/model/shapes/image.cpp \
src/core/model/shapes/precomp_layer.cpp \
src/core/model/shapes/text.cpp \
src/core/model/shapes/repeater.cpp \
src/core/model/shapes/trim.cpp \
src/core/utils/gzip.cpp \
#src/core/utils/trace.cpp \
src/core/utils/quantize.cpp \
src/core/plugin/plugin.cpp \
src/core/plugin/action.cpp \
src/core/plugin/io.cpp \
#src/gui/glaxnimate_app.cpp \
#src/gui/settings/clipboard_settings.cpp \
#src/gui/settings/document_templates.cpp \
#src/gui/settings/toolbar_settings.cpp \
#src/gui/main.cpp \
src/gui/item_models/document_model_base.cpp \
src/gui/item_models/property_model_full.cpp \
src/gui/item_models/property_model_base.cpp \
src/gui/item_models/document_node_model.cpp \
src/gui/item_models/property_model_single.cpp \
src/gui/item_models/gradient_list_model.cpp \
#src/gui/widgets/shape_style/document_swatch_widget.cpp \
#src/gui/widgets/shape_style/gradient_list_widget.cpp \
#src/gui/widgets/shape_style/color_selector.cpp \
#src/gui/widgets/shape_style/fill_style_widget.cpp \
#src/gui/widgets/shape_style/stroke_style_widget.cpp \
#src/gui/widgets/composition_tab_bar.cpp \
#src/gui/widgets/dialogs/gw_impl_debug.cpp \
#src/gui/widgets/dialogs/document_metadata_dialog.cpp \
#src/gui/widgets/dialogs/gw_impl_selection.cpp \
#src/gui/widgets/dialogs/gw_impl_ui.cpp \
#src/gui/widgets/dialogs/timing_dialog.cpp \
#src/gui/widgets/dialogs/gw_impl_document.cpp \
#src/gui/widgets/dialogs/trace_dialog.cpp \
#src/gui/widgets/dialogs/color_quantization_dialog.cpp \
#src/gui/widgets/dialogs/about_dialog.cpp \
#src/gui/widgets/dialogs/resize_dialog.cpp \
#src/gui/widgets/dialogs/clipboard_inspector.cpp \
#src/gui/widgets/dialogs/io_status_dialog.cpp \
#src/gui/widgets/dialogs/shape_parent_dialog.cpp \
#src/gui/widgets/dialogs/glaxnimate_window.cpp \
#src/gui/widgets/dialogs/gw_impl_model.cpp \
#src/gui/widgets/dialogs/plugin_ui_dialog.cpp \
#src/gui/widgets/dialogs/startup_dialog.cpp \
#src/gui/widgets/settings/toolbar_settings_widget.cpp \
#src/gui/widgets/settings/plugin_settings_widget.cpp \
#src/gui/widgets/tab_bar_close_button.cpp \
#src/gui/widgets/flow_layout.cpp \
#src/gui/widgets/spin2d.cpp \
#src/gui/widgets/timeline/frame_controls_widget.cpp \
#src/gui/widgets/timeline/timeline_widget.cpp \
#src/gui/widgets/timeline/keyframe_editor_widget.cpp \
#src/gui/widgets/timeline/timeline_items.cpp \
#src/gui/widgets/timeline/compound_timeline_widget.cpp \
#src/gui/widgets/timeline/keyframe_transition_widget.cpp \
#src/gui/widgets/script_console.cpp \
#src/gui/widgets/clickable_tab_bar.cpp \
#src/gui/widgets/font/font_model.cpp \
#src/gui/widgets/font/font_delegate.cpp \
#src/gui/widgets/font/font_style_dialog.cpp \
#src/gui/widgets/font/font_style_widget.cpp \
#src/gui/widgets/font/font_preview_widget.cpp \
#src/gui/widgets/window_message_widget.cpp \
#src/gui/widgets/node_menu.cpp \
#src/gui/widgets/snippet_list_widget.cpp \
#src/gui/widgets/enum_combo.cpp \
#src/gui/widgets/view_transform_widget.cpp \
#src/gui/widgets/tools/text_tool_widget.cpp \
#src/gui/widgets/tools/color_picker_widget.cpp \
#src/gui/widgets/tools/star_tool_widget.cpp \
#src/gui/widgets/tools/fill_tool_widget.cpp \
#src/gui/widgets/tools/shape_tool_widget.cpp \
#src/gui/widgets/canvas.cpp \
src/gui/style/property_delegate.cpp \
src/gui/style/dock_widget_style.cpp \
src/gui/graphics/gradient_editor.cpp \
src/gui/graphics/transform_graphics_item.cpp \
src/gui/graphics/create_items.cpp \
src/gui/graphics/document_node_graphics_item.cpp \
src/gui/graphics/bezier_item.cpp \
src/gui/graphics/handle.cpp \
src/gui/graphics/document_scene.cpp \
#src/gui/tools/ellipse_tool.cpp \
#src/gui/tools/draw_tool.cpp \
#src/gui/tools/star_tool.cpp \
#src/gui/tools/edit_tool.cpp \
#src/gui/tools/fill_tool.cpp \
#src/gui/tools/color_picker.cpp \
#src/gui/tools/rectangle_tool.cpp \
#src/gui/tools/text_tool.cpp \
#src/gui/tools/base.cpp \
#src/gui/tools/freehand.cpp \
#src/gui/tools/select_tool.cpp

HEADERS = \
external/QtAppSetup/src/app/application.hpp \
external/QtAppSetup/src/app/settings/setting_group.hpp \
external/QtAppSetup/src/app/settings/keyboard_shortcuts.hpp \
external/QtAppSetup/src/app/settings/widget.hpp \
external/QtAppSetup/src/app/settings/keyboard_shortcuts_model.hpp \
external/QtAppSetup/src/app/settings/settings.hpp \
external/QtAppSetup/src/app/settings/widget_builder.hpp \
external/QtAppSetup/src/app/settings/palette_settings.hpp \
external/QtAppSetup/src/app/settings/setting.hpp \
external/QtAppSetup/src/app/settings/custom_settings_group.hpp \
external/QtAppSetup/src/app/translation_service.hpp \
external/QtAppSetup/src/app/utils/qstring_hash.hpp \
external/QtAppSetup/src/app/utils/desktop.hpp \
external/QtAppSetup/src/app/env.hpp \
external/QtAppSetup/src/app/debug/model.hpp \
external/QtAppSetup/src/app/scripting/script_engine.hpp \
external/QtAppSetup/src/app/widgets/settings_dialog.hpp \
external/QtAppSetup/src/app/widgets/keyboard_settings_widget.hpp \
external/QtAppSetup/src/app/widgets/clearable_keysequence_edit.hpp \
external/QtAppSetup/src/app/widgets/widget_palette_editor.hpp \
external/QtAppSetup/src/app/widgets/no_close_on_enter.hpp \
external/QtAppSetup/src/app/cli.hpp \
external/QtAppSetup/src/app/log/listener_stderr.hpp \
external/QtAppSetup/src/app/log/log_model.hpp \
external/QtAppSetup/src/app/log/log_line.hpp \
external/QtAppSetup/src/app/log/logger.hpp \
external/QtAppSetup/src/app/log/log.hpp \
external/QtAppSetup/src/app/log/listener_store.hpp \
external/QtAppSetup/src/app/qstring_exception.hpp \
src/core/plugin/action.hpp \
src/core/plugin/executor.hpp \
src/core/plugin/snippet.hpp \
src/core/plugin/service.hpp \
src/core/plugin/plugin.hpp \
src/core/plugin/io.hpp \
src/core/utils/color.hpp \
src/core/utils/gzip.hpp \
src/core/utils/sort_gradient.hpp \
src/core/utils/pseudo_mutex.hpp \
src/core/utils/regexp.hpp \
#src/core/utils/trace.hpp \
src/core/utils/range.hpp \
src/core/utils/qstring_hash.hpp \
src/core/command/structure_commands.hpp \
src/core/command/shape_commands.hpp \
src/core/command/base.hpp \
src/core/command/property_commands.hpp \
src/core/command/undo_macro_guard.hpp \
src/core/command/object_list_commands.hpp \
src/core/command/animation_commands.hpp \
src/core/io/lottie/tgs_format.hpp \
src/core/io/lottie/lottie_private_common.hpp \
src/core/io/lottie/cbor_write_json.hpp \
src/core/io/lottie/lottie_format.hpp \
src/core/io/lottie/lottie_exporter.hpp \
src/core/io/lottie/lottie_html_format.hpp \
src/core/io/lottie/lottie_importer.hpp \
src/core/io/svg/svg_format.hpp \
src/core/io/svg/svg_html_format.hpp \
src/core/io/svg/svg_mime.hpp \
src/core/io/svg/svg_parser.hpp \
src/core/io/svg/font_weight.hpp \
src/core/io/svg/css_parser.hpp \
src/core/io/svg/animate_parser.hpp \
src/core/io/svg/detail.hpp \
src/core/io/svg/svg_renderer.hpp \
src/core/io/svg/path_parser.hpp \
src/core/io/mime/mime_serializer.hpp \
src/core/io/mime/json_mime.hpp \
src/core/io/io_registry.hpp \
src/core/io/base.hpp \
src/core/io/glaxnimate/glaxnimate_format.hpp \
src/core/io/glaxnimate/glaxnimate_mime.hpp \
src/core/io/glaxnimate/import_state.hpp \
src/core/io/raster/raster_format.hpp \
src/core/io/raster/raster_mime.hpp \
src/core/io/options.hpp \
src/core/application_info_generated.in.hpp \
src/core/model/object.hpp \
src/core/model/mask_settings.hpp \
src/core/model/property/sub_object_property.hpp \
src/core/model/property/reference_property.hpp \
src/core/model/property/object_list_property.hpp \
src/core/model/property/option_list_property.hpp \
src/core/model/property/property.hpp \
src/core/model/assets/bitmap.hpp \
src/core/model/assets/precomposition.hpp \
src/core/model/assets/assets.hpp \
src/core/model/assets/asset.hpp \
src/core/model/assets/asset_base.hpp \
src/core/model/assets/brush_style.hpp \
src/core/model/assets/gradient.hpp \
src/core/model/assets/named_color.hpp \
src/core/model/transform.hpp \
src/core/model/visitor.hpp \
src/core/model/document_node.hpp \
src/core/model/shapes/rect.hpp \
src/core/model/shapes/trim.hpp \
src/core/model/shapes/shape.hpp \
src/core/model/shapes/ellipse.hpp \
src/core/model/shapes/styler.hpp \
src/core/model/shapes/precomp_layer.hpp \
src/core/model/shapes/group.hpp \
src/core/model/shapes/polystar.hpp \
src/core/model/shapes/repeater.hpp \
src/core/model/shapes/image.hpp \
src/core/model/shapes/text.hpp \
src/core/model/shapes/path.hpp \
src/core/model/shapes/layer.hpp \
src/core/model/shapes/stroke.hpp \
src/core/model/shapes/fill.hpp \
src/core/model/animation_container.hpp \
src/core/model/document.hpp \
src/core/model/stretchable_time.hpp \
src/core/model/main_composition.hpp \
src/core/model/animation/frame_time.hpp \
src/core/model/animation/keyframe_transition.hpp \
src/core/model/animation/animatable.hpp \
src/core/model/animation/join_animatables.hpp \
src/core/model/animation/animatable_path.hpp \
src/core/model/comp_graph.hpp \
src/core/model/simple_visitor.hpp \
src/core/model/composition.hpp \
src/core/model/invoke.hpp \
src/core/model/factory.hpp \
src/core/app_info.hpp \
src/core/math/geom.hpp \
src/core/math/math.hpp \
src/core/math/ellipse_solver.hpp \
src/core/math/vector.hpp \
src/core/math/bezier/point.hpp \
src/core/math/bezier/solver.hpp \
src/core/math/bezier/bezier.hpp \
src/core/math/bezier/cubic_struts.hpp \
src/core/math/bezier/segment.hpp \
src/core/math/bezier/operations.hpp \
src/core/math/bezier/meta.hpp \
#src/gui/settings/document_templates.hpp \
#src/gui/settings/plugin_settings_group.hpp \
#src/gui/settings/clipboard_settings.hpp \
#src/gui/settings/toolbar_settings.hpp \
src/gui/item_models/document_model_base.hpp \
src/gui/item_models/property_model_base.hpp \
src/gui/item_models/comp_filter_model.hpp \
src/gui/item_models/asset_proxy_model.hpp \
src/gui/item_models/drag_data.hpp \
src/gui/item_models/property_model_single.hpp \
src/gui/item_models/property_model_private.hpp \
src/gui/item_models/gradient_list_model.hpp \
src/gui/item_models/python_snippet_model.hpp \
src/gui/item_models/document_node_model.hpp \
src/gui/item_models/proxy_base.hpp \
src/gui/item_models/property_model_full.hpp \
#src/gui/widgets/shape_style/shape_style_preview_widget.hpp \
#src/gui/widgets/shape_style/stroke_style_widget.hpp \
#src/gui/widgets/shape_style/document_swatch_widget.hpp \
#src/gui/widgets/shape_style/fill_style_widget.hpp \
#src/gui/widgets/shape_style/gradient_list_widget.hpp \
#src/gui/widgets/shape_style/color_selector.hpp \
#src/gui/widgets/canvas.hpp \
#src/gui/widgets/smaller_spinbox.hpp \
#src/gui/widgets/dialogs/glaxnimate_window.hpp \
#src/gui/widgets/dialogs/trace_dialog.hpp \
#src/gui/widgets/dialogs/keyframe_editor_dialog.hpp \
#src/gui/widgets/dialogs/document_environment.hpp \
#src/gui/widgets/dialogs/document_metadata_dialog.hpp \
#src/gui/widgets/dialogs/timing_dialog.hpp \
#src/gui/widgets/dialogs/glaxnimate_window_p.hpp \
#src/gui/widgets/dialogs/plugin_ui_dialog.hpp \
#src/gui/widgets/dialogs/shape_parent_dialog.hpp \
#src/gui/widgets/dialogs/io_status_dialog.hpp \
#src/gui/widgets/dialogs/about_dialog.hpp \
#src/gui/widgets/dialogs/startup_dialog.hpp \
#src/gui/widgets/dialogs/clipboard_inspector.hpp \
#src/gui/widgets/dialogs/import_export_dialog.hpp \
#src/gui/widgets/dialogs/resize_dialog.hpp \
#src/gui/widgets/dialogs/color_quantization_dialog.hpp \
#src/gui/widgets/settings/plugin_settings_widget.hpp \
#src/gui/widgets/settings/toolbar_settings_widget.hpp \
#src/gui/widgets/node_menu.hpp \
#src/gui/widgets/snippet_list_widget.hpp \
#src/gui/widgets/timeline/frame_controls_widget.hpp \
#src/gui/widgets/timeline/keyframe_editor_widget.hpp \
#src/gui/widgets/timeline/compound_timeline_widget.hpp \
#src/gui/widgets/timeline/timeline_items.hpp \
#src/gui/widgets/timeline/keyframe_transition_widget.hpp \
#src/gui/widgets/timeline/timeline_widget.hpp \
#src/gui/widgets/scalable_button.hpp \
#src/gui/widgets/font/font_delegate.hpp \
#src/gui/widgets/font/font_style_widget.hpp \
#src/gui/widgets/font/font_preview_widget.hpp \
#src/gui/widgets/font/font_style_dialog.hpp \
#src/gui/widgets/font/font_model.hpp \
#src/gui/widgets/tab_bar_close_button.hpp \
#src/gui/widgets/custom_treeview.hpp \
#src/gui/widgets/enum_combo.hpp \
#src/gui/widgets/composition_tab_bar.hpp \
#src/gui/widgets/view_transform_widget.hpp \
#src/gui/widgets/spin2d.hpp \
#src/gui/widgets/window_message_widget.hpp \
#src/gui/widgets/clickable_tab_bar.hpp \
#src/gui/widgets/tools/color_picker_widget.hpp \
#src/gui/widgets/tools/fill_tool_widget.hpp \
#src/gui/widgets/tools/text_tool_widget.hpp \
#src/gui/widgets/tools/star_tool_widget.hpp \
#src/gui/widgets/tools/shape_tool_widget.hpp \
#src/gui/widgets/tools/shape_tool_widget_p.hpp \
#src/gui/widgets/script_console.hpp \
#src/gui/widgets/flow_layout.hpp \
src/gui/style/dock_widget_style.hpp \
src/gui/style/property_delegate.hpp \
src/gui/style/better_elide_delegate.hpp \
src/gui/style/fixed_height_delegate.hpp \
src/gui/graphics/typed_item.hpp \
src/gui/graphics/sizepos_item.hpp \
src/gui/graphics/text_attributes_editor.hpp \
src/gui/graphics/bezier_item.hpp \
src/gui/graphics/main_composition_item.hpp \
src/gui/graphics/rect_rounder.hpp \
src/gui/graphics/create_items.hpp \
src/gui/graphics/document_scene.hpp \
src/gui/graphics/transform_graphics_item.hpp \
src/gui/graphics/shape_graphics_item.hpp \
src/gui/graphics/position_item.hpp \
src/gui/graphics/item_data.hpp \
src/gui/graphics/star_radius_item.hpp \
src/gui/graphics/graphics_editor.hpp \
src/gui/graphics/gradient_editor.hpp \
src/gui/graphics/composition_item.hpp \
src/gui/graphics/handle.hpp \
src/gui/graphics/document_node_graphics_item.hpp \
#src/gui/glaxnimate_app.hpp \
#src/gui/tools/handle_menu.hpp \
#src/gui/tools/edit_tool.hpp \
#src/gui/tools/draw_tool.hpp \
#src/gui/tools/rectangle_tool.hpp \
#src/gui/tools/base.hpp \
#src/gui/tools/draw_tool_drag.hpp \
#src/gui/tools/draw_tool_base.hpp

FORMS = \
external/QtAppSetup/src/app/widgets/keyboard_settings_widget.ui \
external/QtAppSetup/src/app/widgets/settings_dialog.ui \
external/QtAppSetup/src/app/widgets/widget_palette_editor.ui \
external/QtAppSetup/src/app/widgets/clearable_keysequence_edit.ui \
##src/gui/widgets/shape_style/stroke_style_widget.ui \
#src/gui/widgets/shape_style/document_swatch_widget.ui \
##src/gui/widgets/shape_style/color_selector.ui \
##src/gui/widgets/shape_style/gradient_list_widget.ui \
##src/gui/widgets/snippet_list_widget.ui \
##src/gui/widgets/dialogs/document_metadata_dialog.ui \
##src/gui/widgets/dialogs/color_quantization_dialog.ui \
##src/gui/widgets/dialogs/timing_dialog.ui \
##src/gui/widgets/dialogs/io_status_dialog.ui \
##src/gui/widgets/dialogs/resize_dialog.ui \
##src/gui/widgets/dialogs/about_dialog.ui \
##src/gui/widgets/dialogs/startup_dialog.ui \
##src/gui/widgets/dialogs/glaxnimate_window.ui \
##src/gui/widgets/dialogs/trace_dialog.ui \
##src/gui/widgets/dialogs/shape_parent_dialog.ui \
##src/gui/widgets/settings/plugin_settings_widget.ui \
##src/gui/widgets/settings/toolbar_settings_widget.ui \
##src/gui/widgets/timeline/keyframe_editor_widget.ui \
##src/gui/widgets/timeline/frame_controls_widget.ui \
##src/gui/widgets/timeline/compound_timeline_widget.ui \
##src/gui/widgets/font/font_style_widget.ui \
##src/gui/widgets/font/font_style_dialog.ui \
##src/gui/widgets/font/font_preview_widget.ui \
##src/gui/widgets/script_console.ui \
##src/gui/widgets/view_transform_widget.ui \
##src/gui/widgets/tools/color_picker_widget.ui \
##src/gui/widgets/tools/fill_tool_widget.ui \
##src/gui/widgets/tools/shape_tool_widget.ui \
##src/gui/widgets/window_message_widget.ui

RESOURCES = \
build/bin/gui/resources/glaxnimate.qrc

include(external/Qt-Color-Widgets/color_widgets.pri)
include(external/Qt-History-LineEdit/history_lineedit.pri)
